
# eureka.instance.hostname=localhost
# eureka.client.register-with-eureka=false
# eureka.client.fetch-registry=false
# eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
# server.port=8761
# spring.main.web-application-type=reactive

server:
  port: 8761

spring:
  cloud:
    config:
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 5000
        maxAttempts: 20

eureka:
  instance:
    hostname: "${HOSTNAME:localhost}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false