
server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
    
spring:
  
  # application:
  #   name: PRODUCT_SERVICE
  
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/ordersdb
  
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    # when you launch the first time -- switch this from `update` to `create`
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: aSecretKey
  expiration.time: 9000000