apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
  labels:
    app: config-cm
data:
  config_url: "http://config-server-service"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
  labels:
    app: eureka-cm
data:
  eureka_url: "http://serviceregistry:8761/eureka"
