# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name:  discovery-service-dep
#   namespace: default
#   labels:
#     app:  discovery-service-dep
# spec:
#   selector:
#     matchLabels:
#       app: discovery-service-dep
#   replicas: 1
#   # strategy:
#   #   type: Recreate 
#   template:
#     metadata:
#       labels:
#         app:  discovery-service-dep
#     spec:
#       # initContainers:
#         # Init containers are exactly like regular containers, except:
#           # - Init containers always run to completion.
#           # - Each init container must complete successfully before the next one starts.
#       containers:
#       - name:  discovery-service-dep
#         image:  philipasd/discovery-service-v1
#         imagePullPolicy: IfNotPresent
#         # resources:
#         #   requests:
#         #     cpu: 100m
#         #     memory: 100Mi
#         #   limits:
#         #     cpu: 100m
#         #     memory: 100Mi
#         # livenessProbe:
#         #   tcpSocket:
#         #     port: 80
#         #   initialDelaySeconds: 5
#         #   timeoutSeconds: 5
#         #   successThreshold: 1
#         #   failureThreshold: 3
#         #   periodSeconds: 10
#         # readinessProbe:
#         #   httpGet:
#         #     path: /_status/healthz
#         #     port: 80
#         #   initialDelaySeconds: 5
#         #   timeoutSeconds: 2
#         #   successThreshold: 1
#         #   failureThreshold: 3
#         #   periodSeconds: 10
#         ports:
#         - containerPort:  8761
#           name:  discovery-service-dep

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: discovery-service # has to match .spec.template.metadata.labels
  serviceName: "discovery-service"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: discovery-service # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: discovery-service
        image: philipasd/discovery-service-v1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
---
     
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  clusterIP: None
  selector:
    app: discovery-service
  ports:
  - port: 8761
    name: discovery-service

--- 

# Load balancer
apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
spec:
  type: NodePort 
  selector:
    app: discovery-service
  ports:
  - port: 80
    targetPort: 8761