

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-dep
spec:
  selector:
    matchLabels:
      app: product-service-dep
  template:
    metadata:
      labels:
        app: product-service-dep
    spec:
    
      containers:
      - name: product-service-dep
        image: philipasd/product-service-v1:latest
        imagePullPolicy: Always
        ##
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ##
        env:
          - name: CONFIG_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: config-cm
                key: config_url 
                
          - name: database
            valueFrom:
              configMapKeyRef:
                name: postgres-cm
                key: hostname 
        ports:
        - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service-dep
  ports:
  - port: 80
    targetPort: 8082
