apiVersion: apps/v1
kind: Deployment
metadata:
  name:  shopping-cart-dep
  namespace: default
  labels:
    app:  shopping-cart-dep
spec:
  selector:
    matchLabels:
      app: shopping-cart-dep
  replicas: 1
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  template:
    metadata:
      labels:
        app:  shopping-cart-dep
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  shopping-cart-dep
        image:  philipasd/shopping-cart-v1:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: CONFIG_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: config-cm
              key: config_url
        ports:
        - containerPort:  8084
          
---

apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service-dep
  ports:
  - port: 80
    targetPort: 8084
