


server:
    port: 8085
spring: 
    main: 
        web-application-type: reactive
    application:
        name: config_server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/spring-cloud-samples/config-repo
                    # username: philipdaquin
                    # password: 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
                    # uri: https://github.com/philipdaquin/java_microservices
                    # clone-on-start: true


